name = Cars
description = A 3 column layout with a prominent hero region.
preview = preview.png
template = cars-layout

; Regions
regions[navigation]     = Navigation bar
regions[header]         = Header
regions[pre_content]    = Pre-content
regions[hero]           = Hero
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/cars/cars-layout.css
